# Use scratch as fetching image
FROM scratch AS downloads

# Enter toolchains directory
WORKDIR /tmp/toolchains

# Download glibc toolchains
ADD https://toolchains.bootlin.com/downloads/releases/toolchains/x86-64/tarballs/x86-64--glibc--stable-2024.05-1.tar.xz .
ADD https://toolchains.bootlin.com/downloads/releases/toolchains/aarch64/tarballs/aarch64--glibc--stable-2024.05-1.tar.xz .
ADD https://toolchains.bootlin.com/downloads/releases/toolchains/armv5-eabi/tarballs/armv5-eabi--glibc--stable-2024.05-1.tar.xz .
ADD https://toolchains.bootlin.com/downloads/releases/toolchains/mips32/tarballs/mips32--glibc--stable-2024.05-1.tar.xz .
ADD https://toolchains.bootlin.com/downloads/releases/toolchains/mips32el/tarballs/mips32el--glibc--stable-2024.05-1.tar.xz .

# Download musl toolchains
ADD https://toolchains.bootlin.com/downloads/releases/toolchains/x86-64/tarballs/x86-64--musl--stable-2024.05-1.tar.xz .
ADD https://toolchains.bootlin.com/downloads/releases/toolchains/aarch64/tarballs/aarch64--musl--stable-2024.05-1.tar.xz .
ADD https://toolchains.bootlin.com/downloads/releases/toolchains/armv5-eabi/tarballs/armv5-eabi--musl--stable-2024.05-1.tar.xz .
ADD https://toolchains.bootlin.com/downloads/releases/toolchains/mips32/tarballs/mips32--musl--stable-2024.05-1.tar.xz .
ADD https://toolchains.bootlin.com/downloads/releases/toolchains/mips32el/tarballs/mips32el--musl--stable-2024.05-1.tar.xz .

# Download uclibc toolchains
ADD https://toolchains.bootlin.com/downloads/releases/toolchains/x86-64/tarballs/x86-64--uclibc--stable-2024.05-1.tar.xz .
ADD https://toolchains.bootlin.com/downloads/releases/toolchains/aarch64/tarballs/aarch64--uclibc--stable-2024.05-1.tar.xz .
ADD https://toolchains.bootlin.com/downloads/releases/toolchains/armv5-eabi/tarballs/armv5-eabi--uclibc--stable-2024.05-1.tar.xz .
ADD https://toolchains.bootlin.com/downloads/releases/toolchains/mips32/tarballs/mips32--uclibc--stable-2024.05-1.tar.xz .
ADD https://toolchains.bootlin.com/downloads/releases/toolchains/mips32el/tarballs/mips32el--uclibc--stable-2024.05-1.tar.xz .

# Use ubuntu as the base image
FROM ubuntu:22.04

# Install build essentials
RUN apt update && \
	apt install -y build-essential autoconf cmake libtool git qemu-user-static && \
	rm -r /var/lib/apt/lists

# Target directory for toolchains
ARG TOOLCHAINS_DIRECTORY=/toolchains

# Change to the toolchains directory
WORKDIR ${TOOLCHAINS_DIRECTORY}

# Mount toolchains and extract them
RUN --mount=type=bind,from=downloads,source=/tmp/toolchains,target=/tmp/toolchains \
	for file in /tmp/toolchains/*; do \
		tar xf $file; \
	done

# Add environment variable of toolchains location
ENV TOOLCHAINS_DIRECTORY=${TOOLCHAINS_DIRECTORY}

# Copy the resources to the container
COPY --chmod=775 resources /bin

# Change the container entrypoint
ENTRYPOINT [ "entrypoint.sh" ]

# Change to the build working directory
WORKDIR /build